version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src/:/go/src
    tty: true

  nginx:
    image: nginx
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8080:80
    - 443:443
    volumes:
    - ./:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php